(ns ipld.dag-pb-test
  "Conformance fixtures are real blocks, produced by kubo 0.41 with

      ipfs add -Q --cid-version=1 --raw-leaves --chunker=size-N <file>
      ipfs block get <cid>

  and pinned here as hex. Nothing in this file is generated by the encoder
  it tests. That distinction is the point: a codec checked only against its
  own output is self-consistent, which is not the property anyone wants
  from a codec — this workspace already shipped a UnixFS implementation
  that transposed `Links` and `Data`, passed every test, and could not read
  a block written by anything else."
  (:require [clojure.test :refer [deftest is testing]]
            [ipld.dag-pb :as dag-pb]
            [multiformats.core :as mf]))

(defn- unhex [s]
  (mapv (fn [pair]
          (let [s (apply str pair)]
            #?(:clj (Integer/parseInt s 16) :cljs (js/parseInt s 16))))
        (partition 2 s)))

(defn- ->bytes [octets]
  #?(:clj (byte-array (map unchecked-byte octets))
     :cljs (js/Uint8Array.from (into-array octets))))

(defn- hexify [bytes]
  (apply str (map (fn [b]
                    (let [v (bit-and (int b) 0xff)
                          h #?(:clj (Integer/toString v 16)
                               :cljs (.toString v 16))]
                      (if (= 1 (count h)) (str "0" h) h)))
                  (seq bytes))))

;; ── the fixture ───────────────────────────────────────────────────────────
;; A 262,145-byte file: one full 256 KiB chunk plus one byte, so the root is
;; the smallest possible dag-pb node — two raw leaves and a UnixFS file
;; header. Every quirk this codec exists for is visible in these 104 bytes.

(def root-block-hex
  (str "122c"
       "0a2401551220b640ef8d06e11763a7b12c4bfc61fa7be9f6cd109d89cb7d1b91490f1db06133"
       "1200"
       "18808010"
       "122a"
       "0a24015512205d5c7d20a3aab9c158f23304df4bec3bd9d56c517db3caeaa519d4d05624d7a0"
       "1200"
       "1801"
       "0a0c"
       "080218818010208080102001"))

(def root-cid "bafybeibehmsugjvfzrrnrs3katfdixzvvyelnptwbacjw7typ4kht3dmoa")

(def leaf-1-hash-hex
  "01551220b640ef8d06e11763a7b12c4bfc61fa7be9f6cd109d89cb7d1b91490f1db06133")
(def leaf-2-hash-hex
  "015512205d5c7d20a3aab9c158f23304df4bec3bd9d56c517db3caeaa519d4d05624d7a0")

;; UnixFS Data for {type=File, filesize=262145, blocksizes=[262144 1]}. Kept
;; as bytes rather than built here — this namespace is about DAG-PB framing,
;; and the UnixFS layer above it has its own conformance suite.
(def file-data-hex "080218818010208080102001")

(def ^:private fixture-node
  {:links [{:hash (unhex leaf-1-hash-hex) :name "" :tsize 262144}
           {:hash (unhex leaf-2-hash-hex) :name "" :tsize 1}]
   :data (unhex file-data-hex)})

;; ── encode ────────────────────────────────────────────────────────────────

(deftest encodes-a-real-block-byte-for-byte
  (is (= root-block-hex (hexify (dag-pb/encode fixture-node)))))

(deftest addresses-a-real-block
  (is (= root-cid (:cid (dag-pb/node->block fixture-node)))))

(deftest links-are-written-before-data
  (testing "field 2 before field 1 — descending, which protobuf never does"
    (let [octets (mapv #(bit-and (int %) 0xff) (seq (dag-pb/encode fixture-node)))
          first-data (first (keep-indexed (fn [i v] (when (= 0x0a v) i)) octets))]
      (is (= 0x12 (first octets)) "the block opens with field 2 (Links)")
      (is (some? first-data) "Data (field 1) is present")
      (is (pos? first-data) "and it is not first"))))

(deftest an-empty-name-is-written
  (testing "`12 00` is in the block; omitting it changes the CID"
    (let [with-name (dag-pb/encode fixture-node)
          without-name (dag-pb/encode
                        (update fixture-node :links
                                (fn [ls] (mapv #(dissoc % :name) ls))))]
      (is (not= (hexify with-name) (hexify without-name)))
      (is (= root-cid (dag-pb/cid with-name)))
      (is (not= root-cid (dag-pb/cid without-name))
          "a codec that omits the default-valued Name addresses a different block"))))

(deftest link-order-is-the-callers
  (testing "reversing the links is a different file, not a different spelling"
    (is (not= root-cid
              (dag-pb/cid (dag-pb/encode (update fixture-node :links reverse)))))))

(deftest a-link-needs-a-target
  (is (thrown? #?(:clj clojure.lang.ExceptionInfo :cljs js/Error)
               (dag-pb/encode {:links [{:name "x" :tsize 1}]}))))

;; ── decode ────────────────────────────────────────────────────────────────

(deftest decodes-a-real-block
  (let [node (dag-pb/decode (->bytes (unhex root-block-hex)))]
    (is (= 2 (count (:links node))))
    (is (= [262144 1] (mapv :tsize (:links node))))
    (is (= ["" ""] (mapv :name (:links node))))
    (is (= (unhex file-data-hex) (:data node)))
    (is (= (str "b" (mf/base32 (unhex leaf-1-hash-hex)))
           (:cid (first (:links node)))))))

(deftest round-trips-a-real-block
  (let [node (dag-pb/decode (->bytes (unhex root-block-hex)))]
    (is (= root-block-hex (hexify (dag-pb/encode node))))))

(deftest a-transposed-decoder-cannot-read-it
  (testing "the shipped failure, stated as a fact about these bytes"
    ;; Decoding with Links=1 / Data=2 finds one 'link' whose hash is empty:
    ;; it has read the second PBLink submessage as the Data field. Any suite
    ;; whose fixtures came from the same transposed encoder round-trips
    ;; happily and never sees this.
    (let [node (dag-pb/decode (->bytes (unhex root-block-hex)))]
      (is (every? #(= 36 (count (:hash %))) (:links node))
          "a correctly framed link hash is a 36-byte CIDv1"))))
